name: Benchmarks

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Benchmark Check
    runs-on: [ubuntu-20.04, self-hosted]

    env:
      BUILD_DIR: ${{github.workspace}}/build
      BUILD_TYPE: MinSizeRel

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Configure CMake
      run: cmake -G Ninja -B ${{env.BUILD_DIR}} -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --target bvpbenchmark

    - name: Run
      working-directory: ${{env.BUILD_DIR}}/benchmarks
      run: ./bvpbenchmark --benchmark_out_format=json --benchmark_out=benchmark-results.json

    # Workaround for GitHub Markdown (see https://github.com/benchmark-action/github-action-benchmark/issues/167)
    - name: Names Workaround
      working-directory: ${{env.BUILD_DIR}}/benchmarks
      run: sed -i 's/</\&lt;/g;s/>/\&gt;/g' benchmark-results.json

    - name: Download Previous Result
      id: cache-restore
      uses: actions/cache/restore@v3
      with:
        path: ./cache
        key: ignore
        restore-keys: ${{runner.os}}-benchmark-

    - name: Store Result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        name: C++ Benchmark
        tool: 'googlecpp'
        output-file-path: ${{env.BUILD_DIR}}/benchmarks/benchmark-results.json
        external-data-json-path: ./cache/benchmark-results.json
        github-token: ${{secrets.GITHUB_TOKEN}}
        summary-always: true
        # Show alert with commit comment on detecting possible performance regression
        fail-threshold: '150%'
        alert-threshold: '120%'
        comment-on-alert: true
        alert-comment-cc-users: '@eisaev'

    - name: Save Result to Cache
      if: ${{github.ref == 'refs/heads/main'}}
      uses: actions/cache/save@v3
      with:
        path: ./cache
        key: ${{runner.os}}-benchmark-${{github.run_id}}
