name: Coverage PR Comment

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

jobs:
  comment:
    runs-on: [ubuntu-20.04, self-hosted]
    permissions:
      pull-requests: write
    if: ${{github.event.workflow_run.event == 'pull_request'}}
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-results

      - name: Cat Artifact
        run: cat code-coverage-results.md

      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: All
          message: 'Test commit!'

