name: Coverage PR Comment

on:
  workflow_run:
    workflows: ['Coverage']
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.event == 'pull_request'}}
    steps:
#      - name: Download Artifacts
#        id: artifact
#        uses: marocchino/on_artifact@v1
#        with:
#          name: all

      - name: Add PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: All
          message: 'Test commit!'
            #${{steps.artifact.outputs}}
